# Generated by Django 4.2.10 on 2024-03-02 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('Lawyer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('specialization_tags', models.JSONField(default=list)),
                ('profile_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_no', models.PositiveIntegerField()),
                ('license_location', models.CharField(max_length=255)),
                ('license_verify_status', models.BooleanField(default=False)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
        ),
        migrations.CreateModel(
            name='CASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('case_status', models.CharField(choices=[('VICTORY', 'Victory'), ('DEFEAT', 'Defeat')], default='VICTORY', max_length=7)),
                ('case_approval', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.file')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('academic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_degree', models.CharField(max_length=255)),
                ('completion_year', models.PositiveIntegerField()),
                ('major_subject', models.CharField(max_length=255)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.lawyer')),
            ],
        ),
    ]
