# Generated by Django 4.2.10 on 2024-03-05 10:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('location', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('location', models.CharField(max_length=255)),
                ('specialization_tags', models.JSONField(default=list)),
                ('profile_description', models.TextField()),
                ('license_no', models.PositiveIntegerField(null=True)),
                ('license_img', models.ImageField(null=True, upload_to='license_img')),
                ('license_location', models.CharField(max_length=255, null=True)),
                ('license_verify_status', models.BooleanField(default=False)),
                ('academic_degree', models.ImageField(blank=True, null=True, upload_to='academic_degree')),
                ('completion_year', models.PositiveIntegerField(null=True)),
                ('major_subject', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
        ),
        migrations.CreateModel(
            name='CASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('case_status', models.CharField(choices=[('VICTORY', 'Victory'), ('DEFEAT', 'Defeat')], default='VICTORY', max_length=7)),
                ('case_approval', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.file')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.lawyer')),
            ],
        ),
    ]
