# Generated by Django 4.2.10 on 2024-03-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='lawyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.lawyer'),
        ),
        migrations.AlterField(
            model_name='license',
            name='lawyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.lawyer'),
        ),
    ]
