# Generated by Django 4.2.10 on 2024-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
