# Generated by Django 4.2.10 on 2024-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
