# Generated by Django 4.2.10 on 2024-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_lawyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='completion_year',
            field=models.DateField(null=True),
        ),
    ]
