# Generated by Django 4.2.10 on 2024-03-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_file_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='case',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='account.case'),
            preserve_default=False,
        ),
    ]
