# Generated by Django 4.2.10 on 2024-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_academic_lawyer_alter_license_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='lawyer',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='academic_degree',
            field=models.ImageField(blank=True, null=True, upload_to='academic_degree'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='completion_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='license_img',
            field=models.ImageField(null=True, upload_to='license_img'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='license_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='license_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='license_verify_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='major_subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
