# Generated by Django 4.2.10 on 2024-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_lawyer_completion_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
