# Generated by Django 4.2.10 on 2024-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_lawyer_email_lawyer_password_alter_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='specialization_tags',
            field=models.TextField(),
        ),
    ]
