# Generated by Django 4.2.10 on 2024-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_case_case_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
