# Generated by Django 4.2.10 on 2024-03-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_connection_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status_saved',
            field=models.BooleanField(default=False),
        ),
    ]
