# Generated by Django 4.2.10 on 2024-03-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_case_status_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('VICTORY', 'VICTORY'), ('DEFEAT', 'DEFEAT')], default='VICTORY', max_length=7),
        ),
    ]
