# Generated by Django 4.2.10 on 2024-03-06 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_client_id_lawyer_id_alter_lawyer_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
