# Generated by Django 4.2.10 on 2024-03-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_client_id_remove_lawyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetags',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
