# Generated by Django 4.2.10 on 2024-03-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filetags',
        ),
    ]
