# Generated by Django 4.2.10 on 2024-03-13 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_case_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
